### ISSUE TITLE
Add initial documentation

### ISSUE THREAD

**Issue by kushaldas** [SUNET/pkcs11_ca#5]
We can use [sphinx](https://www.sphinx-doc.org/en/master/usage/quickstart.html)

```
$ sphinx-quickstart
```

And then follow the default values.

Also create the readthedocs.org project for the same, and use the hook to publish the documentation there.

- [x] URL to the readthedocs.io for folks to read

Sections/chapters to be added:

- [x] Features available
- [x] Requirements for running in production
- [x] Installation steps/guide
- [x] Usage guide
- [x] Design philosophy 
- [x] All available configuration details
- [x] Example usage

**Comment by vinas003** [comment]
Planned for 29 Mars. With one single use case. ACME.

**Comment by kushaldas** [comment]
As a reference of what we want to become in future (as in documentation), https://github.com/dogtagpki/pki/wiki is a good one I think.
