### ISSUE TITLE
Need corresponding puppet-sunet update for pkcs11_ca

### ISSUE THREAD

**Issue by kushaldas** [SUNET/pkcs11_ca#9]
We need update in the [puppet-sunet](https://github.com/SUNET/puppet-sunet) to deploy this project into a test/production instance.

**Comment by vinas003** [comment]
Preliminary deadline on 8 April due to limited time allocated to this project next week. Expect to take around 8-16 hours of work.

**Comment by vinas003** [comment]
Little late, but no assumed impact for other projects which is late in the first place...
